# Generated by Django 4.1 on 2022-12-04 23:03

from django.db import migrations, models
import e1.models


class Migration(migrations.Migration):

    dependencies = [
        ('e1', '0003_ropa'),
    ]

    operations = [
        migrations.AddField(
            model_name='electro',
            name='foto',
            field=models.ImageField(default='/electronica/electro.png', null=True, upload_to=e1.models.electro.generaNombre),
        ),
        migrations.AlterField(
            model_name='electro',
            name='marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='juguetes',
            name='marca',
            field=models.CharField(max_length=10),
        ),
    ]
