# Generated by Django 4.2.5 on 2023-09-12 14:31

from django.db import migrations, models
import e1.models


class Migration(migrations.Migration):

    dependencies = [
        ('e1', '0004_electro_foto_alter_electro_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electro',
            name='foto',
            field=models.ImageField(default='electronica/electro.png', null=True, upload_to=e1.models.electro.generaNombre),
        ),
    ]
